#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SportLead.Resource", IsApplication=true)]

namespace SportLead
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Logic.Resource.String.ApplicationName = global::SportLead.Resource.String.ApplicationName;
			global::Logic.Resource.String.Hello = global::SportLead.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int theme_custom_background = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ButtonStyle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int EditTextStyle = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int EditTextWhiteStyle = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int LineStyle = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int OK = 2131165184;
			
			// aapt resource value: 0x7f070004
			public const int createAcButton = 2131165188;
			
			// aapt resource value: 0x7f070001
			public const int createAcWindow = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int login = 2131165186;
			
			// aapt resource value: 0x7f070005
			public const int new_login = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int new_password = 2131165190;
			
			// aapt resource value: 0x7f070003
			public const int password = 2131165187;
			
			// aapt resource value: 0x7f070008
			public const int saveSettings = 2131165192;
			
			// aapt resource value: 0x7f070007
			public const int showPasswordCheckBox = 2131165191;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int dialog_sign_up = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int @event = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int login = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int profile = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int settings = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int my_theme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
